//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N3rdyBacon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("N3rdyBacon.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 956660539113738250.
        /// </summary>
        internal static string bot_appid {
            get {
                return ResourceManager.GetString("bot_appid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTU2NjYwNTM5MTEzNzM4MjUw.GFCesn.UZA1hSCW-nduDk5vH70vDndYQzh5Rqd7t5rT0w.
        /// </summary>
        internal static string bot_token {
            get {
                return ResourceManager.GetString("bot_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nrdydesi_n3rdybot.
        /// </summary>
        internal static string db_data {
            get {
                return ResourceManager.GetString("db_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N3rdygamerbr@123.
        /// </summary>
        internal static string db_pass {
            get {
                return ResourceManager.GetString("db_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to db.n3rdydzn.software.
        /// </summary>
        internal static string db_server {
            get {
                return ResourceManager.GetString("db_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to membros.
        /// </summary>
        internal static string db_table {
            get {
                return ResourceManager.GetString("db_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nrdydesi_n3rdydzn.
        /// </summary>
        internal static string db_user {
            get {
                return ResourceManager.GetString("db_user", resourceCulture);
            }
        }
    }
}
